version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update && apt install -y gcc
      - run: gcc -o main main.c -std=c11
      - run: ./main
